# Generated by Django 5.1 on 2024-09-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customusermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
