# Generated by Django 5.1 on 2024-09-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customusermodel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='host',
            field=models.BooleanField(default=False),
        ),
    ]
