# Generated by Django 5.1 on 2024-09-02 16:55

import api.models.roomModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customusermodel_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.roomModel.generate_unique_code, max_length=100, unique=True)),
                ('room_name', models.CharField(default=' ', max_length=100)),
                ('host', models.CharField(default=' ', max_length=100)),
                ('user_can_pass_songs', models.BooleanField(default=False)),
                ('votes_to_switch_type_is_num', models.BooleanField(default=True)),
                ('votes_to_switch', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
