# Generated by Django 5.1 on 2024-09-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_roommodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
