# Generated by Django 5.1 on 2024-09-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_roommodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='users_in_room',
            field=models.IntegerField(default=1),
        ),
    ]
