# Generated by Django 5.1 on 2024-09-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_roommodel_users_in_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_key', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('active_song_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vote_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='roommodel',
            name='active_song_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='active_song_img',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
