# Generated by Django 5.1 on 2024-09-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_uservotesmodel_roommodel_active_song_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_key', models.CharField(max_length=20, unique=True)),
                ('active_song_id', models.CharField(default='', max_length=100)),
                ('active_song_img', models.CharField(default='', max_length=1000)),
                ('host_username', models.CharField(max_length=100)),
                ('dislike', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('request_to_change_genre', models.IntegerField(default=0)),
            ],
        ),
    ]
