# Generated by Django 5.1 on 2024-09-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_votesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='active_song_id',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
