# Generated by Django 5.1 on 2024-09-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_roommodel_active_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='active_song_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
