# Generated by Django 5.1 on 2024-09-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_roommodel_active_song_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestedSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_key', models.CharField(max_length=20)),
                ('suggested_songs_id', models.CharField(default='', max_length=100)),
                ('suggested_songs_img', models.CharField(default='', max_length=1000)),
                ('suggested_by', models.CharField(max_length=20)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
