# Generated by Django 5.1 on 2024-09-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_suggestedsongs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='suggestedSongs',
            new_name='suggestedSongsModel',
        ),
    ]
