# Generated by Django 5.1 on 2024-09-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_suggestedsongs_suggestedsongsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedSongsVotesModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_key', models.CharField(max_length=20)),
                ('suggested_songs_id', models.CharField(default='', max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
