# Generated by Django 5.1 on 2024-09-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_suggestedsongsvotesmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesmodel',
            name='active_song_artists',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='votesmodel',
            name='active_song_is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
