# Generated by Django 5.1 on 2024-09-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_votesmodel_active_song_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesmodel',
            name='active_song_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
