# Generated by Django 5.1 on 2024-09-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_votesmodel_active_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='active_song_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
