# Generated by Django 5.1 on 2024-09-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_roommodel_active_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedsongsmodel',
            name='suggested_song_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
