# Generated by Django 5.1 on 2024-09-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_suggestedsongsmodel_suggested_song_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongsQueueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_key', models.CharField(max_length=20)),
                ('songs_id', models.CharField(default='', max_length=100)),
                ('song_title', models.CharField(default='', max_length=100)),
                ('songs_img', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
