# Generated by Django 5.1 on 2024-09-13 00:09

import spotify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_rename_user_spotifytoken_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='user_token_id',
            field=models.CharField(default=spotify.models.random_id, max_length=100),
        ),
    ]
